TeamsTab/Models/ErrorViewModel.cs
using System;

namespace TeamsTab.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TeamsTab/Controllers/TabController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TeamsTab.Models;

namespace TeamsTab.Controllers
{
    public class TabController : Controller
    {
        private readonly ILogger<TabController> _logger;

        public TabController(ILogger<TabController> logger)
        {
            _logger = logger;
        }

        public IActionResult Configuration()
        {
            return View();
        }

        public IActionResult Content()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeamsTab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeamsTab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src='https://statics.teams.cdn.office.net/sdk/v1.7.0/js/MicrosoftTeams.min.js' integrity="sha384-00JbifySIlPvW32u9rSurgu8PujfL6XFdV9iNn4ZWyurJJ33MFvpwPqmCHDq9ADv" crossorigin="anonymous"></script>
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Tab" asp-action="Content">TeamsTab</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tab" asp-action="Configuration">Configuration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tab" asp-action="Content">Content</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TeamsTab - <a asp-area="" asp-controller="Home" asp-action="Content">Content</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TeamsTab/Views/Tab/Configuration.cshtml
@{
    ViewData["Title"] = "ConfigurationTab";
}

<h1>ConfigurationTab</h1>

<button onclick="initializeTeamSettings()">initialize team settings</button>

<script>
    function initializeTeamSettings() {
        microsoftTeams.initialize();
        microsoftTeams.settings.setValidityState(true);
        microsoftTeams.settings.registerOnSaveHandler((saveEvent) => {
            microsoftTeams.settings.setSettings({
                websiteUrl: "<REPLACE THIS WITH YOUR LOCAL TUNNEL ADDRESS, eg https://2d9ee7096e08.ngrok.io>",
                contentUrl: "<REPLACE THIS WITH YOUR LOCAL TUNNEL ADDRESS, eg https://2d9ee7096e08.ngrok.io>/Tab/Content",
                entityId: "contentTab",
                suggestedDisplayName: "Content"
            });
            saveEvent.notifySuccess();
        });
    }
</script>

TeamsTab/Views/Tab/Content.cshtml
@{
    ViewData["Title"] = "Content Page";
}
<h1>@ViewData["Title"]</h1>

<p>This is the Content Page for the Teams App</p>
<button onclick="showContextInfo()">show context info</button>
<button onclick="showMeetingDetails()">show meeting details</button>

<script type="text/javascript">
    function showContextInfo() {
        microsoftTeams.initialize();

        microsoftTeams.getContext(function (context) {
            var teamName = context.teamName;
            alert("Team Name: " + teamName + "\n" +
                "Team ID: " + context.teamId + "\n" +
                "Channel ID: " + context.channelId + "\n" +
                "Chat ID: " + context.chatId + "\n" +
                "Session ID: " + context.sessionId + "\n" +
                "Channel Name: " + context.channelName + "\n" +
                "Locale: " + context.locale + "\n" +
                "Entity ID:" + context.entityId + "\n" +
                "User Principal Name: " + context.userPrincipalName + "\n" +
                "T ID: " + context.tid + "\n" +
                "Group ID: " + context.groupId + "\n" +
                "Theme: " + context.theme + "\n" +
                "Is Full Screen: " + context.isFullScreen + "\n" +
                "Team Type: " + context.teamType + "\n" +
                "User Team Role: " + context.userTeamRole + "\n" +
                "Host Client Type: " + context.hostClientType + "\n" +
                "Frame Context: " + context.frameContext + "\n" +
                "Meeting ID:" + context.meetingId);
        });
    }

    function showMeetingDetails() {
        alert("show meeting details button clicked");
        microsoftTeams.initialize();

        var members = microsoftTeams.getChatMembers();
        alert(members);
    }
</script>